version: '2'

services:

  # METEOR

  # Meteor
  meteor:
    container_name: "openmetadesign-meteor"
    build:
      context: ./app/
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://MONGOUSERNAME:MONGOPASSWORD@mongo:27017/meteor

  # MONGO

  # Mongo DB
  mongo:
    container_name: "openmetadesign-mongo-meteor"
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=MONGOADMINUSERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD=MONGOADMINPASSWORD"
      - "MONGO_INITDB_DATABASE=admin"

    volumes:
      - mongo:/data
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger


volumes:
  mongo:
