version: '2'

services:

  # METEOR

  # Meteor
  meteor:
    container_name: "openmetadesign-meteor"
    build:
      context: ./app/
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/meteor

  # MONGO

  # Mongo DB
  mongo:
    container_name: "openmetadesign-mongo-meteor"
    image: mongo:latest
    hostname: mongodb
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=MONGOUSERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD=MONGOPASSWORD"
      - "MONGO_INITDB_DATABASE=MONGODB"

    volumes:
      - mongo:/data
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger


volumes:
  mongo:
